myfatoorah_symfony_create:
    path: /myfatoorah/create
    controller: MyFatoorah\SymfonyBundle\Controller\InvoiceController::create
    
myfatoorah_symfony_callback:
    path: /myfatoorah/callback
    controller: MyFatoorah\SymfonyBundle\Controller\InvoiceController::callback