myfatoorah_create:
    path: /myfatoorah/create
    controller: MyFatoorah\Symfony\Controller\Invoice::create
    
myfatoorah_callback:
    path: /myfatoorah/callback
    controller: MyFatoorah\Symfony\Controller\Invoice::callback